# Generated by Django 4.1.1 on 2022-09-29 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrimerMVT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiares',
            old_name='apellido',
            new_name='parentesco',
        ),
    ]
